# Generated by Django 5.2.14 on 2026-05-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("release_year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "rating",
                    models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
                ),
                ("description", models.TextField(blank=True)),
                ("poster_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="movies.genre"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movies",
                        to="movies.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "title"],
                "indexes": [
                    models.Index(
                        fields=["language", "rating"], name="idx_language_rating"
                    ),
                    models.Index(
                        fields=["release_year", "rating"], name="idx_year_rating"
                    ),
                    models.Index(
                        fields=["language", "release_year"], name="idx_language_year"
                    ),
                ],
            },
        ),
    ]
